# Generated by Django 6.0.2 on 2026-03-03 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('methode', models.CharField(choices=[('mobile_money', 'Mobile Money'), ('carte_bancaire', 'Carte Bancaire'), ('especes', 'Espèces'), ('virement', 'Virement Bancaire')], default='mobile_money', max_length=20)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('reussie', 'Réussie'), ('echouee', 'Échouée'), ('remboursee', 'Remboursée')], default='en_attente', max_length=20)),
                ('reference_transaction', models.CharField(blank=True, help_text='Référence externe de la transaction (ex: ID Mobile Money)', max_length=100, null=True, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='paiement', to='orders.order')),
            ],
            options={
                'verbose_name': 'paiement',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['commande', 'statut'], name='payments_pa_command_c82149_idx'), models.Index(fields=['-created_at'], name='payments_pa_created_3147e3_idx')],
            },
        ),
    ]
