sonar.projectKey=agrimarket
sonar.projectName=agrimarket
sonar.sources=config,users,products,orders,payments,dashboard
sonar.tests=users,products,orders,payments,dashboard
sonar.test.inclusions=**/tests.py,**/test_*.py
sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8
