"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
import os


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-2somr_4h*eqn#b!uj5=tfoxza8+2$w!wta(0vokkus3gq=opk*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Local apps
    'users',
    'products',
    'orders',
    'payments',
    'dashboard',

    # THIRD PARTY APPS
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'drf_spectacular',
    'corsheaders',
    'django_filters',

]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # Doit être en haut pour gérer les CORS avant les autres middlewares
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        'ATOMIC_REQUESTS': True,
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'Africa/Abidjan'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'

MEDIA_ROOT = BASE_DIR / 'media'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'users.User'

REST_FRAMEWORK = {
    
    # Mon API utilise JWT pour authentifier les utilisateurs
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],

    # Par défaut, seuls les utilisateurs authentifiés peuvent accéder aux ressources protégées(endpoints) de mon API
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],

    # Limite le nombre de requêtes que les utilisateurs peuvent faire à mon API pour éviter les abus
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],

    # Définit les taux de limitation pour les utilisateurs anonymes et authentifiés
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/day',
        'user': '2000/day',
        'register': '10/hour',
    },

    # Permet aux utilisateurs de filtrer, rechercher et trier les données de mon API facilement
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],

    # Définit la pagination par défaut pour les listes de ressources dans mon API
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,

    # Utilise drf-spectacular pour générer automatiquement la documentation de mon API
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',

}

JWT_SIGNING_KEY = os.environ.get('JWT_SIGNING_KEY', '6b57a99e3de2a72641cbc6e8e451959879948ff0254a89e5a5f132af49faa8be')
SIMPLE_JWT = {
    # Durées de vie : plus courtes pour limiter l'impact en cas de vol
    # Access token : 15 minutes (suffisant pour une session interactive)
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    # Refresh token : 1 jour (à ajuster selon votre besoin métier)
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),

    # Rotation des refresh tokens : à chaque utilisation, un nouveau refresh token est émis
    # et l'ancien devient inutilisable. Empêche l'usage prolongé d'un token volé.
    'ROTATE_REFRESH_TOKENS': True,

    # Blacklist après rotation : les anciens refresh tokens sont ajoutés à une liste noire
    # (nécessite l'app installée 'rest_framework_simplejwt.token_blacklist')
    'BLACKLIST_AFTER_ROTATION': True,

    # Algorithme de signature : HS256 avec une clé dédiée (la plus simple et sécurisée)
    # Pour une architecture microservices, préférez RS256 (asymétrique) - voir variante plus bas
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': JWT_SIGNING_KEY,   # Utilise la clé définie ci-dessus
    # 'VERIFYING_KEY' n'est pas nécessaire en HS256

    # Audience et émetteur : restreignent l'usage du token à votre API
    'AUDIENCE': 'http://localhost:8000',
    'ISSUER': 'http://localhost:8000',

    # Identification de l'utilisateur
    'USER_ID_FIELD': 'id',            # Champ du modèle User
    'USER_ID_CLAIM': 'user_id',       # Nom du claim dans le token

    # Types de tokens autorisés (seulement AccessToken, pas de SlidingToken)
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),

    # Noms des claims standards
    'TOKEN_TYPE_CLAIM': 'token_type', # Pour distinguer access/refresh
    'JTI_CLAIM': 'jti',               # Identifiant unique du token (utile pour la blacklist)

    # Mise à jour automatique du champ last_login de l'utilisateur à chaque nouveau token
    'UPDATE_LAST_LOGIN': True,

    # En-tête d'autorisation attendu (Bearer <token>)
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# Configuration de drf-spectacular pour personnaliser la documentation de mon API
SPECTACULAR_SETTINGS = {
    'TITLE': 'AgriMarket API',
    'DESCRIPTION': 'API REST de Gestion de Marché Agricole',
    'VERSION': '1.0.0',
    # Ça indique que la documentation de mon API est disponible à l’URL /api/schema/ et que je peux utiliser Swagger UI pour visualiser et tester les endpoints de mon API
    'SERVE_INCLUDE_SCHEMA': False,
}

# CORS (Cross-Origin Resource Sharing) settings pour permettre à mon frontend de faire des requêtes à mon API depuis des domaines différents
CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',
    'http://localhost:5173',
]

#SECURE_BROWSER_XSS_FILTER = True # Active le filtre XSS intégré dans les navigateurs pour protéger contre les attaques de type cross-site scripting
#SECURE_CONTENT_TYPE_NOSNIFF = True # Empêche les navigateurs de deviner le type de contenu et d'exécuter du code malveillant
#X_FRAME_OPTIONS = 'DENY' # Empêche mon site d'être affiché dans une iframe pour éviter les attaques de clickjacking